### ISSUE TITLE
ValueError: could not broadcast input array from shape (0,) into shape (0,2)

### ISSUE THREAD

**Issue by Edison2021** [firasmidani/amiga#7]
Hi Firas

Got an error below 

Traceback (most recent call last):
  File "/home/manager/src/amiga-master/amiga.py", line 392, in <module>
    AMiGA()
  File "/home/manager/src/amiga-master/amiga.py", line 90, in __init__
    getattr(self, args.command)()
  File "/home/manager/src/amiga-master/amiga.py", line 210, in fit
    Command(args).fit()
  File "/home/manager/src/amiga-master/libs/commands.py", line 114, in fit
    runGrowthFitting(data,mappings,self.directory,args,verbose=args.verbose)
  File "/home/manager/src/amiga-master/libs/analyze.py", line 168, in runGrowthFitting
    sub_plate.model(nthin=args.time_step_size,store=store,verbose=verbose)
  File "/home/manager/src/amiga-master/libs/growth.py", line 705, in model
    curve = gm.run(name=sample_id)
  File "/home/manager/src/amiga-master/libs/model.py", line 249, in run
    curve = GrowthCurve(x=time,y=actual_input,y0=self.y0,y1=self.y1,y2=self.y2,
  File "/home/manager/src/amiga-master/libs/curve.py", line 132, in __init__
    self.describe()
  File "/home/manager/src/amiga-master/libs/curve.py", line 192, in describe
    dx = detectDiauxie(self.x,self.y0,self.y1,self.y2,self.cov0,self.cov1,
  File "/home/manager/src/amiga-master/libs/diauxie.py", line 88, in detectDiauxie
    ret[:,4:6] = [[y1[l-1],y1[r-1]] for l,r in bounds]     # growth rate at both bounds 
ValueError: could not broadcast input array from shape (0,) into shape (0,2)

What kind of problems caused the error?

Thanks
Edison

**Comment by firasmidani** [comment]
Hmm, error suggests that there is a problem with the function that detects diauxic shifts. My best guess is that your data set has a particular growth curve with a weird behavior that the function has not seen before and does not know how to handle. But it's hard to tell without replicating the error myself. 

Can you try to re-run your command with the `--verbose` argument? This will help you determine which well in which file or plate causes the problem. If you share that particular growth curve with me here, I can try to replicate the error. You can also share the whole file with me too instead.

**Comment by Edison2021** [comment]
The problem has been solved. Thanks

**Comment by Edison2021** [comment]
Well E9 seems to cause the problem and the OD values are below

E9	0.1513	0.1597	0.1643	0.1798	0.212	0.2444	0.3553

**Comment by firasmidani** [comment]
Thanks for sharing your data. I was able to replicate the error and it was a fairly simple fix. Please re-install AMiGA and run again. If you cloned the repository, you can simply `git pull`, otherwise, just simply replace the old amiga folder with the new one. Let me know if that fixes the problem.

**Comment by Edison2021** [comment]
Thanks for your prompt response. It is working now,
